"""Domain models for CuLoRA.

Business entity models and data structures.
"""

from .clip import (
    BatchSemanticResult,
    ClusteringResult,
    DiversityAnalysis,
    EmbeddingSimilarity,
    SemanticAnalysisResult,
    SemanticCluster,
    SemanticEmbedding,
    SemanticSelectionCriteria,
    SemanticSelectionResult,
)
from .composition import (
    BatchCompositionResult,
    CompositionAnalysis,
    CompositionResult,
)
from .config import (
    CLIPConfig,
    CompositionConfig,
    CuLoRAConfig,
    DeviceConfig,
    FaceAnalysisConfig,
    ImageConfig,
    PoseConfig,
    QualityConfig,
)
from .device import Device
from .duplicate import (
    DuplicateAnalysis,
    DuplicateConfig,
    DuplicateGroup,
    DuplicateMatch,
    DuplicateRemovalStrategy,
    DuplicateThreshold,
    HashAlgorithm,
    ImageHash,
)
from .face import BatchFaceAnalysisResult, FaceAnalysisResult, FaceDetection
from .face_reference import (
    ReferenceEmbedding,
    ReferenceImage,
    ReferenceMatchResult,
    ReferenceProcessingResult,
    ReferenceSet,
    SimilarityMatch,
)
from .image import BatchLoadResult, DirectoryScanResult, ImageLoadResult, ImageMetadata
from .memory import Memory
from .pose import (
    BatchPoseResult,
    PoseAnalysis,
    PoseAnalysisResult,
    PoseClassification,
    PoseCluster,
    PoseClusteringResult,
    PoseDiversityAnalysis,
    PoseLandmark,
    PoseSelectionCriteria,
    PoseSelectionResult,
    PoseSimilarity,
    PoseVector,
)
from .quality import (
    BatchQualityResult,
    ImageQualityResult,
    QualityScore,
    TechnicalQualityMetrics,
)

__all__ = [
    "BatchCompositionResult",
    "BatchFaceAnalysisResult",
    "BatchLoadResult",
    "BatchPoseResult",
    "BatchQualityResult",
    "BatchSemanticResult",
    "CLIPConfig",
    "ClusteringResult",
    "CompositionAnalysis",
    "CompositionConfig",
    "CompositionResult",
    "CuLoRAConfig",
    "Device",
    "DeviceConfig",
    "DirectoryScanResult",
    "DiversityAnalysis",
    "DuplicateAnalysis",
    "DuplicateConfig",
    "DuplicateGroup",
    "DuplicateMatch",
    "DuplicateRemovalStrategy",
    "DuplicateThreshold",
    "EmbeddingSimilarity",
    "FaceAnalysisConfig",
    "FaceAnalysisResult",
    "FaceDetection",
    "HashAlgorithm",
    "ImageConfig",
    "ImageHash",
    "ImageLoadResult",
    "ImageMetadata",
    "ImageQualityResult",
    "Memory",
    "PoseAnalysis",
    "PoseAnalysisResult",
    "PoseClassification",
    "PoseCluster",
    "PoseClusteringResult",
    "PoseConfig",
    "PoseDiversityAnalysis",
    "PoseLandmark",
    "PoseSelectionCriteria",
    "PoseSelectionResult",
    "PoseSimilarity",
    "PoseVector",
    "QualityConfig",
    "QualityScore",
    "ReferenceEmbedding",
    "ReferenceImage",
    "ReferenceMatchResult",
    "ReferenceProcessingResult",
    "ReferenceSet",
    "SemanticAnalysisResult",
    "SemanticCluster",
    "SemanticEmbedding",
    "SemanticSelectionCriteria",
    "SemanticSelectionResult",
    "SimilarityMatch",
    "TechnicalQualityMetrics",
]
